import { KonciaceSkoleniaRow, EmployeeData, Fa, Kava, Pravomoc } from "./types";

export const DUMMY_DATA: EmployeeData[] = [
  {
    meno: "Adam",
    priezvisko: "Maly",
    pravomoc: Pravomoc.PRACOVNIK,
    pozicia: "xy",
    fa: Fa.AGENTURA,
    oblast: "oblast1",
    osobne_cislo: 123,
    karticka: 123,
    kava: Kava.NIE,
    bufetka: 32,
    zfsatna: 43,
    zfskrinka: undefined,
    winnex: undefined,
  },
  {
    meno: "Filip",
    priezvisko: "Novy",
    pravomoc: Pravomoc.NADRIADENY,
    oblasti: ["Oblast1, Oblast2"],
    pozicia: "ds",
    fa: Fa.AGENTURA,
    oblast: "Oblast2",
    osobne_cislo: 32,
    karticka: 231,
    kava: Kava.ANO,
    bufetka: 32,
    zfsatna: undefined,
    zfskrinka: undefined,
    winnex: 213,
  },
  {
    meno: "Adam",
    priezvisko: "Maly",
    pravomoc: Pravomoc.PRACOVNIK,
    pozicia: "",
    fa: Fa.LEASING,
    oblast: "Oblast2",
    osobne_cislo: 45,
    karticka: 2311,
    kava: Kava.NIE,
    bufetka: 23,
    zfsatna: undefined,
    zfskrinka: undefined,
    winnex: 11,
  },
  {
    meno: "Adam",
    priezvisko: "Maly",
    pravomoc: Pravomoc.PRACOVNIK,
    pozicia: "xy",
    fa: Fa.AGENTURA,
    oblast: "oblast1",
    osobne_cislo: 123,
    karticka: 123,
    kava: Kava.NIE,
    bufetka: 32,
    zfsatna: 43,
    zfskrinka: undefined,
    winnex: undefined,
  },
  {
    meno: "Filip",
    priezvisko: "Novy",
    pravomoc: Pravomoc.NADRIADENY,
    oblasti: ["Oblast1, Oblast2"],
    pozicia: "ds",
    fa: Fa.AGENTURA,
    oblast: "Oblast2",
    osobne_cislo: 32,
    karticka: 231,
    kava: Kava.ANO,
    bufetka: 32,
    zfsatna: undefined,
    zfskrinka: undefined,
    winnex: 213,
  },
  {
    meno: "Adam",
    priezvisko: "Maly",
    pravomoc: Pravomoc.PRACOVNIK,
    pozicia: "",
    fa: Fa.LEASING,
    oblast: "Oblast2",
    osobne_cislo: 45,
    karticka: 2311,
    kava: Kava.NIE,
    bufetka: 23,
    zfsatna: undefined,
    zfskrinka: undefined,
    winnex: 11,
  },
  {
    meno: "Adam",
    priezvisko: "Maly",
    pravomoc: Pravomoc.PRACOVNIK,
    pozicia: "xy",
    fa: Fa.AGENTURA,
    oblast: "oblast1",
    osobne_cislo: 123,
    karticka: 123,
    kava: Kava.NIE,
    bufetka: 32,
    zfsatna: 43,
    zfskrinka: undefined,
    winnex: undefined,
  },
  {
    meno: "Filip",
    priezvisko: "Novy",
    pravomoc: Pravomoc.NADRIADENY,
    oblasti: ["Oblast1, Oblast2"],
    pozicia: "ds",
    fa: Fa.AGENTURA,
    oblast: "Oblast2",
    osobne_cislo: 32,
    karticka: 231,
    kava: Kava.ANO,
    bufetka: 32,
    zfsatna: undefined,
    zfskrinka: undefined,
    winnex: 213,
  },
  {
    meno: "Adam",
    priezvisko: "Maly",
    pravomoc: Pravomoc.PRACOVNIK,
    pozicia: "",
    fa: Fa.LEASING,
    oblast: "Oblast2",
    osobne_cislo: 45,
    karticka: 2311,
    kava: Kava.NIE,
    bufetka: 23,
    zfsatna: undefined,
    zfskrinka: undefined,
    winnex: 11,
  },
  {
    meno: "Adam",
    priezvisko: "Maly",
    pravomoc: Pravomoc.PRACOVNIK,
    pozicia: "xy",
    fa: Fa.AGENTURA,
    oblast: "oblast1",
    osobne_cislo: 123,
    karticka: 123,
    kava: Kava.NIE,
    bufetka: 32,
    zfsatna: 43,
    zfskrinka: undefined,
    winnex: undefined,
  },
  {
    meno: "Filip",
    priezvisko: "Novy",
    pravomoc: Pravomoc.NADRIADENY,
    oblasti: ["Oblast1, Oblast2"],
    pozicia: "ds",
    fa: Fa.AGENTURA,
    oblast: "Oblast2",
    osobne_cislo: 32,
    karticka: 231,
    kava: Kava.ANO,
    bufetka: 32,
    zfsatna: undefined,
    zfskrinka: undefined,
    winnex: 213,
  },
  {
    meno: "Adam",
    priezvisko: "Maly",
    pravomoc: Pravomoc.PRACOVNIK,
    pozicia: "",
    fa: Fa.LEASING,
    oblast: "Oblast2",
    osobne_cislo: 45,
    karticka: 2311,
    kava: Kava.NIE,
    bufetka: 23,
    zfsatna: undefined,
    zfskrinka: undefined,
    winnex: 11,
  },
];

export const expCourses: KonciaceSkoleniaRow[] = [
  {
    datum: new Date(),
    pocetDniPlatnosti: 9,
    skolenie: 'xx',
    osobne_cislo: 12,
    priezvisko: "Ferko",
    meno: "Jan",
    nadriadeny: "Maly",
  },
  {
    datum: new Date(),
    pocetDniPlatnosti: 9,
    skolenie: 'xx',
    osobne_cislo: 12,
    priezvisko: "Ferko",
    meno: "Jan",
    nadriadeny: "Maly",
  },
  {
    datum: new Date(),
    pocetDniPlatnosti: 0,
    skolenie: 'xx',
    osobne_cislo: 13,
    priezvisko: "Silny",
    meno: "Filip",
    nadriadeny: "Maly",
  },
  {
    datum: new Date(),
    pocetDniPlatnosti: 14,
    skolenie: 'xx',
    osobne_cislo: 14,
    priezvisko: "Janko",
    meno: "Jan",
    nadriadeny: "Maly",
  },

]
